### ISSUE TITLE
[REQ] Automated download for individual episodes or complete seasons

### ISSUE THREAD

**Issue by Spectroxx** [xcscxr/nineanime-grabber#2]
Would you be willing to add a download prompt allowing a user to download an episode or complete season instead of manually visiting each stream link?

For example:
 - Enter URL or query
 - Select the  item you want
 - Chose the service
 - Chose the episode or for a full season you could type "all'
 - Download prompt "Would you like to download these Episode(s) y | n"

**Comment by xcscxr** [comment]
Downloader is out of scope of this project since it's just a stream url grabber. Maybe in future will add a module but not anytime soon.

**Comment by scrazzz** [comment]
@xcscxr how would you integrate a downloader in this project? Would you use ffmpeg, ytdl or something else?

**Comment by w0lfrm** [comment]
> @xcscxr how would you integrate a downloader in this project? Would you use ffmpeg, ytdl or something else?

use pysmart-dl or just use requests with tqdm(for progress bar) on the direct download link you get from the script
